const _words = [
	'cron',
	'ls',
	'cd',
	'df',
	'traceroute',
	'map',
	'reduce',
	'javascript',
	'typescript',
	'lua',
	'emacs',
	'vim',
	'ping',
	'document',
	'window',
	'writeFileSync',
	'chmod',
	'toLocaleDateString',
	'vscode',
	'recover',
	'if',
	'del',
	'flocinaucinihilipilification', // lmao
	'iterm2',
	'value',
	'operator',
	'true',
	'default',
	'async',
	'short',
	'new',
	'constructor',
	'bug',
	'async',
	'dependency',
	'for',
	'eventListener',
	'stdio',
	'reference',
	'object',
	'unsafe',
	'as',
	'node',
	'encodeURI',
	'element',
	'dislocate',
	'quotastats',
	'string',
	'xargs',
	'typeof',
	'function',
	'lastIndexOf',
	'indexof',
	'md5sum',
	'unix2dos',
	'propertyIsEnumerable',
	'propertyIsWritable',
	'__defineGetter__',
	'man',
	'java',
	'c++',
	'gcc',
	'g++',
	'make',
	'algorithm',
	'arrays',
	'argument',
	'lisp',
	'parameter',
	'autonomous',
	'binary',
	'vimscript',
	'fortran',
	'conditional',
	'integrated',
	'development',
	'environment',
	'jupyter',
	'linux',
	'git',
	'tty',
	'alacritty',
	'script',
	'DocumentObjectModel',
	'DOM',
	'data',
	'database',
	'emmet',
	'nodejs',
	'deno',
	'npm',
	'express',
	'RegExp',
	'addEventListener',
	'removeEventListener',
	'variable',
	'model',
	'view',
	'controller',
	'angular',
	'reactjs',
	'vue',
	'svelte',
	'abstraction',
	'agile',
	'AJAX',
	'ASCII',
	'bootstrap',
	'jQuery',
	'process.env',
	'console',
	...Object.getOwnPropertyNames(Math),
	...Object.getOwnPropertyNames(Object),
	...Object.getOwnPropertyNames(Array),
	...Object.getOwnPropertyNames(Array.prototype),
	...Object.getOwnPropertyNames(String),
	...Object.getOwnPropertyNames(String.prototype),
	// ...Object.getOwnPropertyNames(Proxy),
//	...Object.getOwnPropertyNames(Function),
//	...Object.getOwnPropertyNames(Function.prototype),
//	...Object.getOwnPropertyNames(Error),
//	...Object.getOwnPropertyNames(Error.prototype),
//	...Object.getOwnPropertyNames(Number),
//	...Object.getOwnPropertyNames(Number.prototype),
//	...Object.getOwnPropertyNames(Map),
//	...Object.getOwnPropertyNames(Map.prototype),
//	...Object.getOwnPropertyNames(Set),
//	...Object.getOwnPropertyNames(Set.prototype),
//	...Object.getOwnPropertyNames(BigUint64Array),
//	...Object.getOwnPropertyNames(JSON),
//	...Object.getOwnPropertyNames(Reflect),
];

const words = [...new Set(_words)];

const getWord = () => words[Math.floor(Math.random() * words.length)];

module.exports = getWord;
module.exports.words = words;
