const words = [
	'cron',
	'ls',
	'cd',
	'df',
	'traceroute',
	'map',
	'reduce',
	'javascript',
	'typescript',
	'lua',
	'emacs',
	'vim',
	'ping',
	'document',
	'window',
	'writefilesync',
	'chmod',
	'tolocaledatestring',
	'vscode',
	'recover',
	'if',
	'del',
	'flocinaucinihilipilification', // lmao
	'iterm2',
	'value',
	'operator',
	'true',
	'default',
	'async',
	'short',
	'new',
	'constructor',
	'bug',
	'async',
	'dependency',
	'for',
	'eventlistener',
	'stdio',
	'reference',
	'object',
	'unsafe',
	'as',
	'node',
	'encodeuri',
	'element',
	'dislocate',
	'quotastats',
	'string',
	'xargs',
	'typeof',
	'function',
	'lastindexof',
	'indexof',
	'md5sum',
	'unix2dos',
	'propertyisenumerable',
	'propertyiswritable',
	'__definegetter__',
];

// returns a bunch of words for the new frame.
// number of words increases exponentially with the number of frames

const getWord = () => words[Math.floor(Math.random() * words.length) + 1];

module.exports = getWord;
module.exports.words = words;
